services:
  candidate:
    build: microservices/candidate-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_0,kafka
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      mongodb:
        condition: service_healthy
      kafka:
        condition: service_started

  candidate-p1:
    build: microservices/candidate-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_1,kafka
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      mongodb:
        condition: service_healthy
      kafka:
        condition: service_started

  comment:
    build: microservices/comment-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_0,kafka
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      mongodb:
        condition: service_healthy
      kafka:
        condition: service_started

  comment-p1:
    build: microservices/comment-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_1,kafka
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      mongodb:
        condition: service_healthy
      kafka:
        condition: service_started

  news-article:
    build: microservices/news-article-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_0,kafka
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started

  news-article-p1:
    build: microservices/news-article-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_1,kafka
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started

  candidate-composite:
    build: microservices/candidate-composite-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,kafka
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      kafka:
        condition: service_started
    
  mongodb:
    image: mongo:8.2.1
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "27017:27017"
    command: mongod
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 2s
      retries: 60

  mysql:
    image: mysql:8.4.7
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=newsarticle-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pwd --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 60

  kafka:
    image: confluentinc/cp-kafka:7.9.4
    restart: always
    deploy:
      resources:
        limits:
          memory: 1024M
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.4
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

  eureka:
    build: springcloud/eurekaserver
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "8761:8761"



