services:
  candidate:
    build: microservices/candidate-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  comment:
    build: microservices/comment-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  newsarticle:
    build: microservices/news-article-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  candidate-composite:
    build: microservices/candidate-composite-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      rabbitmq:
        condition: service_healthy
      authserver:
        condition: service_healthy
    
  mongodb:
    image: mongo:8.2.1
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "27017:27017"
    command: mongod
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 2s
      retries: 60

  mysql:
    image: mysql:8.4.7
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=newsarticle-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pwd --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 60

  rabbitmq:
    image: rabbitmq:4.2.0-management
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 2s
      retries: 60

  eureka:
    build: springcloud/eurekaserver
    deploy:
      resources:
        limits:
          memory: 512M

  gateway:
    build: springcloud/gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "8443:8443"
    depends_on:
      authserver:
        condition: service_healthy

  authserver:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build: springcloud/authserver
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ["CMD", "wget", "-O -", "-q", "http://localhost:9999/actuator/health"]
      interval: 5s
      timeout: 2s
      retries: 60
