spring.application.name: comment-service
server.port: 7002
server.error.include-message: always

spring.data.mongodb:
  host: localhost
  port: 27017
  database: comment-db

logging:
  level:
    root: INFO
    pe.elections.microservices: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

---
spring.config.activate.on-profile: docker
server.port: 8080
spring.data.mongodb.host: mongodb
